load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "challenge_lib",
    srcs = ["server.go"],
    importpath = "github.com/corvad/pow/services/challenge",
    visibility = ["//visibility:private"],
    deps = [
        "//api/proto:challenge_go_proto",
        "@com_github_google_uuid//:uuid",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//reflection",
    ],
)

go_binary(
    name = "challenge",
    embed = [":challenge_lib"],
    visibility = ["//visibility:public"],
)
